-- Bootstrap schema required by conformance nightly workflows.
-- Scope intentionally minimal for issues #181-#183.

CREATE TABLE IF NOT EXISTS public.goldset_questions_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    gold_answer TEXT,
    gold_sources TEXT,
    theme TEXT,
    source TEXT,
    goldset_name TEXT,
    comment TEXT,
    original_turn_id TEXT,
    difficulty TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT goldset_questions_v2_question_key UNIQUE (question),
    CONSTRAINT goldset_questions_v2_difficulty_check CHECK (
        difficulty IS NULL OR difficulty IN ('easy', 'medium', 'hard')
    )
);

CREATE INDEX IF NOT EXISTS idx_goldset_questions_v2_goldset_name
    ON public.goldset_questions_v2 (goldset_name);

CREATE INDEX IF NOT EXISTS idx_goldset_questions_v2_goldset_name_id
    ON public.goldset_questions_v2 (goldset_name, id);

CREATE INDEX IF NOT EXISTS idx_goldset_questions_v2_tags
    ON public.goldset_questions_v2 USING GIN (tags);
